project:
  type: website

website:
  title: "Niyazi Kemer"
  navbar:
    right:
      - about.qmd
      - icon: mastodon
        text: Mastodon
        href: https://sigmoid.social/@niyazi
      - icon: github
        href: https://github.com/niyazikemer
      - icon: twitter
        href: https://twitter.com/niyazi_kemer
      
format:
  html:
    theme: cosmo
    css: styles.css



